version: "3.3"
services:
  workshop-bet-app-mysql:
    build: ./devOps/docker/mysql
    container_name: workshop-bet-app-mysql
    image: workshop-bet-app-mysql
    ports:
      - "3312:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file: .env
  workshop-bet-ui:
    container_name: workshop-bet-ui
    image: workshop-bet-ui
    ports:
      - "80:80"
  workshop-bet-app-bet-service:
    depends_on:
      - workshop-bet-app-mysql
      - workshop-bet-app-rabbit-mq
    container_name: workshop-bet-app-bet-service
    image: workshop-bet-app-bet-service:latest
    ports:
      - "8181:8181"
      - "8001:8001"
  workshop-bet-app-antifraud-service:
    depends_on:
      - workshop-bet-app-mysql
      - workshop-bet-app-rabbit-mq
    container_name: workshop-bet-app-antifraud-service
    image: workshop-bet-app-antifraud-service:latest
    ports:
      - "8182:8182"
      - "8002:8002"
  workshop-bet-app-rabbit-mq:
    container_name: workshop-bet-app-rabbit-mq
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
