version: "3.3"
services:
  workshop-bet-app-mysql:
    container_name: workshop-bet-app-mysql
    image: workshop-bet-app-mysql:latest
    ports:
      - "3312:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file: .env
  workshop-bet-app-rabbit-mq:
    container_name: workshop-bet-app-rabbit-mq
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
  workshop-bet-app-adm-panel:
    #build: ./panel
    container_name: workshop-bet-app-adm-panel
    image: workshop-bet-app-adm-panel:latest
    ports:
      - "80:80"
    depends_on:
      - workshop-bet-app-mysql
      - workshop-bet-app-adm-panel
  workshop-place-bet:
    #build: ./panel
    container_name: workshop-place-bet
    image: workshop-place-bet:latest
    ports:
      - "8181:8181"
      - "8001:8001"
    depends_on:
      - workshop-bet-app-mysql
      - workshop-bet-app-adm-panel
  workshop-retrieve-bet:
    #build: ./panel
    container_name: workshop-retrieve-bet
    image: workshop-retrieve-bet:latest
    ports:
      - "8182:8181"
      - "8002:8001"
    depends_on:
      - workshop-bet-app-mysql
      - workshop-bet-app-adm-panel

