version: "3.3"
services:
  workshop-bet-app-mysql:
    build: ./devOps/docker/mysql
    container_name: workshop-bet-app-mysql
    image: workshop-bet-app-mysql
    ports:
      - "3312:3306"
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    env_file: .env
  workshop-bet-app-rabbit-mq:
    container_name: workshop-bet-app-rabbit-mq
    image: rabbitmq:management
    ports:
      - "15672:15672"
      - "5672:5672"
  workshop-bet-app-admin-panel:
    build: ./admin-panel
    container_name: workshop-bet-app-admin-panel
    image: workshop-bet-app-admin-panel
    ports:
      - "80:80"
  workshop-bet-app-place-bet:
    build: ./place-bet
    container_name: workshop-bet-app-place-bet
    image: workshop-bet-app-place-bet:latest
    ports:
      - "8181:8181"
      - "8001:8001"
  workshop-bet-app-retrieve-bet:
    build: ./retrieve-bet
    container_name: workshop-bet-app-retrieve-bet
    image: workshop-bet-app-retrieve-bet:latest
    ports:
      - "8182:8182"
      - "8002:8001"
